# YAML - IaaC (Infrastructure as a Code)

version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: beetroot-postgres
    environment:
      POSTGRES_DB: beetroot-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - c-sharp-107-local-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: beetroot-pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - c-sharp-107-local-network
    restart: unless-stopped

networks:
  c-sharp-107-local-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
